### ISSUE TITLE
Stop getting logs in kibana after sometime

### ISSUE THREAD

**Issue by msalmanmasood** [centos-opstools/centos-release-opstools#4]
systemctl status fluentd -l returns following messages:

 [warn]: temporarily failed to flush the buffer. next_retry=2018-08-01 06:04:50 +0300 error_class="Fluent::ElasticsearchOutput::ConnectionFailure" error="Can not reach Elasticsearch cluster ({:host=>\"localhost\", :port=>9200, :scheme=>\"http\"})! read timeout reached" plugin_id="object:5fd9bc"

**Comment by richm** [comment]
curl -v -s http://localhost:9200

**Comment by msalmanmasood** [comment]
curl -v -s http://localhost:9200
* About to connect() to localhost port 9200 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 9200 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:9200
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=UTF-8
< Content-Length: 367
<
{
  "name" : "Frank Simpson",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "4K2zYWiQSUqF0UJ-SQZ2sA",
  "version" : {
    "number" : "2.4.5",
    "build_hash" : "c849dd13904f53e63e88efc33b2ceeda0b6a1276",
    "build_timestamp" : "2017-04-24T16:18:17Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.4"
  },
  "tagline" : "You Know, for Search"
}
* Connection #0 to host localhost left intact

However, fluentd service is complaining as:

systemctl status fluentd -l
● fluentd.service - Fluentd
   Loaded: loaded (/usr/lib/systemd/system/fluentd.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2018-07-31 13:39:24 +03; 1 weeks 1 days ago
     Docs: http://www.fluentd.org/
 Main PID: 29876 (fluentd)
   CGroup: /system.slice/fluentd.service
           ├─29876 /usr/bin/ruby /usr/bin/fluentd -c /etc/fluentd/fluent.conf
           └─29878 /usr/bin/ruby /usr/bin/fluentd -c /etc/fluentd/fluent.conf

Aug 09 01:45:59 noreplys.xyz.net fluentd[29876]: 2018-08-09 01:45:59 +0300 [warn]: temporarily failed to flush the buffer. next_retry=2018-08-09 02:02:55 +0300 error_class="Elasticsearch::Transport::Transport::Error" error="Cannot get new connection from pool." plugin_id="object:a74c98"
Aug 09 01:45:59 noreplys.xyz.net fluentd[29876]: 2018-08-09 01:45:59 +0300 [warn]: suppressed same stacktrace
Aug 09 02:02:57 noreplys.xyz.net fluentd[29876]: 2018-08-09 02:02:57 +0300 [warn]: temporarily failed to flush the buffer. next_retry=2018-08-09 02:41:09 +0300 error_class="Elasticsearch::Transport::Transport::Error" error="Cannot get new connection from pool." plugin_id="object:a74c98"
Aug 09 02:02:57 noreplys.xyz.net fluentd[29876]: 2018-08-09 02:02:57 +0300 [warn]: suppressed same stacktrace
Aug 09 02:41:11 noreplys.xyz.net fluentd[29876]: 2018-08-09 02:41:11 +0300 [warn]: temporarily failed to flush the buffer. next_retry=2018-08-09 03:56:03 +0300 error_class="Elasticsearch::Transport::Transport::Error" error="Cannot get new connection from pool." plugin_id="object:a74c98"
Aug 09 02:41:11 noreplys.xyz.net fluentd[29876]: 2018-08-09 02:41:11 +0300 [warn]: suppressed same stacktrace
Aug 09 03:56:06 noreplys.xyz.net fluentd[29876]: 2018-08-09 03:56:06 +0300 [warn]: temporarily failed to flush the buffer. next_retry=2018-08-09 06:00:42 +0300 error_class="Elasticsearch::Transport::Transport::Error" error="Cannot get new connection from pool." plugin_id="object:a74c98"
Aug 09 03:56:06 noreplys.xyz.net fluentd[29876]: 2018-08-09 03:56:06 +0300 [warn]: suppressed same stacktrace
Aug 09 06:00:44 noreplys.xyz.net fluentd[29876]: 2018-08-09 06:00:44 +0300 [warn]: temporarily failed to flush the buffer. next_retry=2018-08-09 11:04:58 +0300 error_class="Elasticsearch::Transport::Transport::Error" error="Cannot get new connection from pool." plugin_id="object:a74c98"
Aug 09 06:00:44 noreplys.xyz.net fluentd[29876]: 2018-08-09 06:00:44 +0300 [warn]: suppressed same stacktrace
[root@noreplys ~]#


As per our observation same issue is happening recurrently after 2 or 3 days or max it works for a week and then we need to restart the fluentd services.. any idea what is happening here?

Thanks.

**Comment by richm** [comment]
I think it has to do with https://github.com/uken/fluent-plugin-elasticsearch/tree/v0.12#reload_connections

try setting `reload_connections false`
