### ISSUE TITLE
graphite-manage syncdb --noinput is failing!!

### ISSUE THREAD

**Issue by msalmanmasood** [centos-opstools/centos-release-opstools#6]
Using new versions repos for kibana and elasticsearch and the deployment is failing:

fatal: [monlog]: FAILED! => {"changed": true, "cmd": ["su", "apache", "-s", "/bin/bash", "-c", "/usr/bin/graphite-manage syncdb --noinput"], "delta": "0:00:00.673162", "end": "2019-01-08 16:43:42.848740", "msg": "non-zero return code", "rc": 1, "start": "2019-01-08 16:43:42.175578", "stderr": "Unknown command: 'syncdb'\nType 'graphite-manage help' for usage.", "stderr_lines": ["Unknown command: 'syncdb'", "Type 'graphite-manage help' for usage."], "stdout": "", "stdout_lines": []}

**Comment by mrunge** [comment]
Thanks for the report.

I must admit, we moved away from graphite to use prometheus. iirc, there was a change in Django/graphite to set up the database, this is documented here: https://graphite.readthedocs.io/en/latest/config-database-setup.html

**Comment by msalmanmasood** [comment]
Thanks for the response.

So the new change is not updated as yet in the code? from where I can get the updated git repo which may help me running all in one like a charm?

Many Thanks.

**Comment by mrunge** [comment]
Which change?

This repo here is only about the centos-release-opstools repository file.

You are more than welcome to send patches to https://github.com/centos-opstools/opstools-ansible 
see https://opstools-ansible.readthedocs.io/en/latest/developers.html
